### ISSUE TITLE
[Newsletter] link

### ISSUE THREAD

**Issue by fmmricardo** [cooperativa-tech/minhocovid19#45]
Envelope icon is missing on mobile version.
Browser: Firefox

![Screenshot 2020-05-02 at 13 43 06](https://user-images.githubusercontent.com/20669868/80864530-2a7e2e80-8c7b-11ea-8b9a-8c668d0efeed.png)

**Comment by jfranciscosousa** [comment]
Can't replicate. Is this on Firefox app on mobile?

**Comment by fmmricardo** [comment]
Sorry, mobile version 320 px width

**Comment by jfranciscosousa** [comment]
Fixed on #48
