### ISSUE TITLE
[Newsletter] Input

### ISSUE THREAD

**Issue by fmmricardo** [cooperativa-tech/minhocovid19#46]
Suggestion: 
apply the same height we are using for the buttons on mobile version, which is : `52px` 

actual implementation:
![Screenshot 2020-05-02 at 13 52 20](https://user-images.githubusercontent.com/20669868/80864742-77163980-8c7c-11ea-92ae-d6e46caf6aaa.png)

Suggestions:
height:52px
font-size:16px
line-height:20px
![Screenshot 2020-05-02 at 13 54 21](https://user-images.githubusercontent.com/20669868/80864743-78dffd00-8c7c-11ea-8311-0134943fc14a.png)

**Comment by jfranciscosousa** [comment]
Won't set the height as fixed, should match 52 with the paddings and line-height though. Fixed on #48
